spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:file:./appdb
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      format_sql: true
      show_sql: true

logging:
  level:
#    root: WARN
    org.springframework: INFO
    org.hibernate: INFO
    com.emlakjet: DEBUG

graphql:
  annotations.base-package: com.emlakjet.videostore.graphql
  graphiql:
    enabled: true
    pageTitle: Video Management System
  schema-strategy: annotations
