spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:file:./appdb
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      format_sql: true
      show_sql: true

logging:
  level:
    root: WARN
    org.springframework: INFO
    com.zaxxer: WARN
    org.hibernate: INFO
    com.emlakjet: DEBUG
    com.graphql-java-kickstart: DEBUG

graphql:
  annotations.base-package: com.emlakjet.videostore.graphql
  extended-scalars: BigDecimal, Date, DateTime, Long
  graphiql:
    enabled: true
    pageTitle: Video Management System
    headers:
      Authorization: "Bearer YWRtaW46cGFzcw=="
  schema-strategy: annotations
